
services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./src/core/logs/error_logs:/app/error_logs
      - ./src/core/logs/request_logs:/app/request_logs
    depends_on:
      - redis
      - elasticsearch
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - ELASTICSEARCH_HOST=es01
  celery:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./src/core/logs/error_logs:/app/error_logs
      - ./src/core/logs/request_logs:/app/request_logs
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
    command:
      ["sh", "-c", "pdm run mail"]

  redis:
      image: redis
      ports:
        - "6379:6379"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.0
    container_name: es01
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    mem_limit: 1g

  kibana:
    image: docker.elastic.co/kibana/kibana:9.0.0
    container_name: kib01
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:9.0.0
    container_name: filebeat
    depends_on:
      - elasticsearch
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./src/core/logs:/logs:ro

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app

  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/app/static  # map static files (update path accordingly)
      - ./media:/app/media    # if you have media files
    depends_on:
      - app