filebeat.inputs:
  - type: filestream
    enabled: true
    paths:
      - /logs/request_logs/*.log
      - /logs/error_logs/*.log
    parsers:
      - ndjson:
          target: ""
          add_error_key: true
          expand_keys: true

output.elasticsearch:
  hosts: ["https://es01:9200"]
  protocol: "https"
  ssl.verification_mode: "none"
  username: "elastic"
  password: "+YTQDmL5HFhfB*5f1EJU"

setup.kibana:
  host: "https://kib01:5601"
  protocol: "https"
  ssl.verification_mode: "none"
